service: nest-serverless-lambda-demo
plugins:
  - 'serverless-plugin-typescript'
  - 'serverless-plugin-optimize'
  - 'serverless-offline'
  - 'serverless-dotenv-plugin'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  iam:
    role: arn:aws:iam::315199840269:policy/TeamFiveLambdaExecution
    deploymentRole: arn:aws:iam::315199840269:policy/TeamFiveServerless

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    timeout: 30
    handler: ./src/lambda.handler
    events:
      - sqs:
          arn: arn:aws:sqs:ap-northeast-2:315199840269:area.fifo
          batchSize: 10
