service: nest-serverless-lambda-demo
plugins:
  - 'serverless-plugin-typescript'
  - 'serverless-plugin-optimize'
  - 'serverless-offline'
  - 'serverless-dotenv-plugin'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: ./src/lambda.handler
    events:
      - sqs:
          arn: arn:aws:sqs:ap-northeast-2:315199840269:area.fifo
          batchSize: 10
